### ISSUE TITLE
Not working at all since version 1805 of Azure Stack....

### ISSUE THREAD

**Issue by hakksaww1** [Azure-Samples/AzureStack-AdminPowerShell-OMSIntegration#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Attempt to use on Azure Stack 1805 release. As written there are also several dependencies that are omitted from Azure Stack powershell (operations related) that can be installed manually but the main issue is post-1805, multiple issues with upload and retrieval of information on both the Azure Stack and OpsInsight side.

### Any log messages given by the failure
>
Get-AzureRmOperationalInsightsWorkspace : The 'Get-AzureRmOperationalInsightsWorkspace' command
was found in the module 'AzureRM.OperationalInsights', but the module could not be loaded. For
more information, run 'Import-Module AzureRM.OperationalInsights'.
At C:\AZSAdminOMSInt\OpsDataToOMS.ps1:87 char:7
+ $ws = Get-AzureRmOperationalInsightsWorkspace -ResourceGroupName $OMS ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureRmOperationalInsightsWorkspace:String) []
   , CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

No Alerts From  + Rack30
[
    {
        "ScaleUnitNodeName":  "SAC30-Node01",
        "ScaleUnitNodeOperationalStatus":  null,
        "ScaleUnitNodeLocation":  "rack30",
        "Type":  "ScaleUnitNode",
        "TimeStamp":  "\/Date(1533829587185)\/",
        "ScaleUnitNodeandCloudName":  "SAC30-Node01_Rack30",
        "CloudName":  "Rack30"
    },
    {
        "ScaleUnitNodeName":  "SAC30-Node02",
        "ScaleUnitNodeOperationalStatus":  null,
        "ScaleUnitNodeLocation":  "rack30",
        "Type":  "ScaleUnitNode",
        "TimeStamp":  "\/Date(1533829587185)\/",
        "ScaleUnitNodeandCloudName":  "SAC30-Node02_Rack30",
        "CloudName":  "Rack30"
    },
    {
        "ScaleUnitNodeName":  "SAC30-Node03",
        "ScaleUnitNodeOperationalStatus":  null,
        "ScaleUnitNodeLocation":  "rack30",
        "Type":  "ScaleUnitNode",
        "TimeStamp":  "\/Date(1533829587185)\/",
        "ScaleUnitNodeandCloudName":  "SAC30-Node03_Rack30",
        "CloudName":  "Rack30"
    },
    {
        "ScaleUnitNodeName":  "SAC30-Node04",
        "ScaleUnitNodeOperationalStatus":  null,
        "ScaleUnitNodeLocation":  "rack30",
        "Type":  "ScaleUnitNode",
        "TimeStamp":  "\/Date(1533829587185)\/",
        "ScaleUnitNodeandCloudName":  "SAC30-Node04_Rack30",
        "CloudName":  "Rack30"
    },
    {
        "Version":  null,
        "IPPoolAvail":  null,
        "MemoryUsed":  null,
        "DiskAvail":  null,
        "State":  null,
        "Location":  "Rack30",
        "Type":  "Capacity",
        "MemoryAvail":  null,
        "CloudName":  "Rack30",
        "DiskUsed":  null,
        "IPPoolUsed":  null,
        "TimeStamp":  "\/Date(1533829587169)\/",
        "DeploymentGuid":  "706a85ca-abf3-4866-8667-d967bcb68797"
    }
]
PS>TerminatingError(Send-OMSAPIIngestionFile): "Cannot bind argument to parameter 'customerId' because it is null."
Send-OMSAPIIngestionFile : Cannot bind argument to parameter 'customerId' because it is null.
At C:\AZSAdminOMSInt\OpsDataToOMS.ps1:233 char:38
+ Send-OMSAPIIngestionFile -customerId $ws.CustomerId -sharedKey $wskey ...
+                                      ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-OMSAPIIngestionFile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Send-OMSAPIIngestionFile
Send-OMSAPIIngestionFile : Cannot bind argument to parameter 'customerId' because it is null.
At C:\AZSAdminOMSInt\OpsDataToOMS.ps1:233 char:38
+ Send-OMSAPIIngestionFile -customerId $ws.CustomerId -sharedKey $wskey ...
+                                      ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-OMSAPIIngestionFile], ParameterBindingValida
   tionException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Send-OMSAPIIngestion
   File

### Expected/desired behavior
>This was working great up until 1804.

### OS and Version?
> Azure Stack version 
1.1805.1.47 

### Versions
>
1.1805.1.47

**Comment by ashika789** [comment]
Hi hakksaww1 - the files have been updated to reflect a change in a previously broken commandlet. Please download the new InvokeMasterScript.ps1 and MasterScript.ps1 files and try again. Be sure to delete any previous folder named \AZSAdminOMSInt from the C:\ folder. Also remove previously created scheduled tasks from "Task Scheduler"
