### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by peternewman** [Azure-Samples/AzureStack-AdminPowerShell-OMSIntegration#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> See https://github.com/Azure-Samples/AzureStack-AdminPowerShell-OMSIntegration/search?q=onmicrsoft.com&unscoped_q=onmicrsoft.com

### Any log messages given by the failure
>

### Expected/desired behavior
> onmicrosoft.com

Found while investigating https://github.com/codespell-project/codespell/issues/676

**Comment by IanB111** [comment]
Corrected the spelling in the examples

**Comment by peternewman** [comment]
Thanks @IanB111 !
